#!/usr/bin/env python

import rospy
import sys

from mrplan_auctioneer.auctioneer import Auctioneer


if __name__ == '__main__':
    try:
        argv = rospy.myargv(argv=sys.argv[1:])
        auc = Auctioneer(*argv)
    except rospy.ROSInterruptException:
        pass

